/* Ask PA Réalt · Fiafraigh: answers built ONLY from this site's own data and cited sources.
   Per-type templates for every mapped monument + hand-written answers for the featured sites.
   Nothing is generated by an AI; where our sources are silent, the answer says "not known". */
(function(){
const A=window.PAAstro,D=Math.PI/180;
Object.assign(window.PA_SRC,{
  scope:["National Monuments Service (2023). Monument Class and Scope Notes, v1.1 (bilingual).","https://www.archaeology.ie/collections-and-publications/publications/monument-class-and-scope-notes/"],
  smr:["National Monuments Service. Sites and Monuments Record, description of this monument (CC BY 4.0).","https://data.gov.ie/dataset/national-monuments-service-archaeological-survey-of-ireland"],
  nismr:["Northern Ireland Sites and Monuments Record, DfC Historic Environment Division (OGL v3).","https://www.data.gov.uk/dataset/46240fa5-db15-469e-b1c8-0460504b951c/northern-ireland-sites-and-monuments-record"],
  care:["National Monuments Service (2009). National Monuments in State Care: Ownership & Guardianship (county lists).","https://www.archaeology.ie/"],
  tailte:["Tailte Éireann. Townlands, National Statutory Boundaries 2019 (CC BY 4.0).","https://gsi.geodata.gov.ie/server/rest/services/Third_Party/IE_GSI_Tailte_Eireann_Townlands_IE26_ITM/FeatureServer/0"],
  logainm:["Logainm.ie: Placenames Database of Ireland (Fiontar & Scoil na Gaeilge, DCU, and the Placenames Branch).","https://www.logainm.ie/"],
  focloir:["Foras na Gaeilge. New English–Irish Dictionary, focloir.ie.","https://www.focloir.ie/"],
  hiBnB:["Heritage Ireland (OPW). Brú na Bóinne Visitor Centre: Newgrange, Knowth and Dowth.","https://heritageireland.ie/places-to-visit/bru-na-boinne-visitor-centre-newgrange-knowth-and-dowth/"],
  hiLC:["Heritage Ireland (OPW). Loughcrew Megalithic Cemetery.","https://heritageireland.ie/places-to-visit/loughcrew-megalithic-cemetery/"],
  oirLC:["Dáil Éireann, written answer 562, 4 Nov 2025 (Cairn T closed since Oct 2018).","https://www.oireachtas.ie/en/debates/question/2025-11-04/562/"],
  hiCM:["Heritage Ireland (OPW). Carrowmore Megalithic Cemetery.","https://heritageireland.ie/places-to-visit/carrowmore-megalithic-cemetery/"],
  hiDB:["Heritage Ireland (OPW). Drombeg Stone Circle.","https://heritageireland.ie/unguided-sites/drombeg-stone-circle/"],
  research:["PA Réalt RESEARCH.md and pre-registered tests (prereg/tests_v1.json).","https://github.com/Sliothar1/pa-realt/blob/main/RESEARCH.md"]
});
const QS=[
 ['face','Does it face a sunrise or moonrise?','An dtugann sé aghaidh ar éirí gréine nó gealaí?'],
 ['when','Who built it, and when?','Cé a thóg é, agus cathain?'],
 ['real','Is the alignment real or coincidence?','Fíor nó comhtharlú?'],
 ['name','What’s the Irish name, and what does it mean?','Ainm Gaeilge agus a bhrí'],
 ['visit','What can I see if I visit?','Cad atá le feiceáil?']
];
/* era used for each class (Earth's tilt then), from the NMS scope-note date ranges */
const ERA={pt:[-3199,'c. 3200 BC'],ct:[-3749,'c. 3750 BC'],po:[-3499,'c. 3500 BC'],mu:[-2999,'c. 3000 BC (class spans 4000–500 BC)'],wt:[-2249,'c. 2250 BC'],
  sc:[-1499,'c. 1500 BC'],sr:[-1499,'c. 1500 BC'],sp:[-1499,'c. 1500 BC'],he:[-2249,'c. 2250 BC'],cu:[-3199,'c. 3200 BC'],bb:[-1499,'c. 1500 BC'],ss:[-1499,'c. 1500 BC']};
/* class-level evidence on orientation, quoting only our cited sources */
const TYPE_ORIENT={
 pt:['The national survey of passage tombs (NMS 2024, F. Prendergast) could measure 136 of about 220. 23 are aligned on some solar or lunar target, but only 4 face the midwinter sunrise, and there is no overall clustering (global p = 0.896). Our smaller pre-registered test T2 (36 tombs: compass phrases from SMR texts plus 2 surveyed axes) did find more tombs near solstice, equinox and standstill declinations than chance (Holm-adjusted p = 0.019). The two results disagree, and the larger survey carries more weight.',['ng2024','research']],
 wt:['The NMS scope note says the front of a wedge tomb “invariably faces in a westerly direction”. Our pre-registered test T1 (scored 9 Oct 2026) found 19 of the 51 wedge tombs with a recorded facing direction in the south-west bin that holds the midwinter sunset, against about 3 expected by chance (Holm-adjusted p = 0.0005). That shows a strong south-west to west preference, but not that the builders aimed at the Sun.',['scope','research']],
 sr:['The NMS scope note says stone rows “are considered to have been aligned on various solar and lunar events”. Clive Ruggles’s surveys of the Cork–Kerry rows found a preference for the Moon’s southern major and minor standstills, often towards prominent hills. Our pre-registered replication on 119 SMR stone rows (T3) found no excess: 6 rows near a standstill declination, against 5.9 expected by chance.',['scope','ruggles94','research']],
 sp:['The NMS scope note says stone pairs “are considered to have been aligned on various solar and lunar events”. Ruggles’s surveys of Cork–Kerry stone rows found a lunar (southern standstill) preference. Our pre-registered test T5 found that pair and row axes point at horizon peaks no more often than random directions do (58.8% against 59.7%).',['scope','ruggles94','research']],
 sc:['Ruggles (1994) tested 31 Cork–Kerry axial-stone circles and found no solstice or equinox pattern, only a weak cluster near declination −29° (6 of 31). In the NMS scope note the axial stone sits “consistently in the south-western part of the circle”.',['ruggles94','scope']],
 ss:['The NMS scope note says single standing stones are “usually orientated on a north-east–south-west axis, although other orientations do occur”. A single stone has no direction it clearly points in, so astronomical claims are weak.',['scope']],
 ct:['Our sources give no tested orientation pattern for court tombs, so this is not known from our data.',[]],
 po:['Our sources give no tested orientation pattern for portal tombs, so this is not known from our data.',[]],
 mu:['This tomb could not be assigned to a type, and our sources give no orientation pattern, so this is not known.',[]],
 he:['Our sources give no tested orientation pattern for Irish henges, so this is not known.',[]],
 cu:['Our sources give no tested orientation pattern for Irish cursus monuments, so this is not known.',[]],
 bb:['Our sources give no tested orientation pattern for boulder-burials, so this is not known.',[]]
};
const TEST={pt:'T2 (passage-tomb declinations) and T4 (intervisibility)',wt:'T1 (wedge tombs and the setting Sun)',sr:'T3 (stone rows and the lunar standstills) and T5 (horizon peaks)',sp:'T5 (horizon peaks)',sc:null,ss:null};
const PT16={N:0,NNE:22.5,NE:45,ENE:67.5,E:90,ESE:112.5,SE:135,SSE:157.5,S:180,SSW:202.5,SW:225,WSW:247.5,W:270,WNW:292.5,NW:315,NNW:337.5};
const pt16=az=>Object.keys(PT16)[Math.round(((az%360)+360)%360/22.5)%16];
const decOf=(az,lat,prof)=>{const h=prof?A.horAt(prof,az):0,ht=h-A.refr(h);return Math.asin(Math.sin(lat*D)*Math.sin(ht*D)+Math.cos(lat*D)*Math.cos(ht*D)*Math.cos(az*D))/D;}; // real (or flat) horizon, Sun's centre with refraction
let TR=null;const tres=()=>TR||(TR=fetch('data/tests_v1.json').then(r=>r.json()).catch(()=>null));
let KB=null;const NOTES={};
async function kb(){if(!KB)KB=await fetch('data/ask_kb.json').then(r=>r.json());return KB;}
async function notesFor(s){if(s[0].startsWith('NI:'))return null;const c=s[6];if(!(c in NOTES))NOTES[c]=fetch('data/notes/c'+c+'.json').then(r=>r.json()).catch(()=>({}));const n=await NOTES[c];return n[s[0]]||null;}
const esc=t=>String(t==null?'':t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const src=keys=>keys.filter(k=>window.PA_SRC[k]).map(k=>{const s=window.PA_SRC[k];return s[1]?`<a href="${s[1]}" target="_blank" rel="noopener">${esc(s[0].split('.')[0].split(':')[0])}</a>`:esc(s[0].split('.')[0]);}).join(' · ');
const sentences=t=>String(t||'').replace(/\n+/g,' ').split(/(?<=[.;])\s+(?=[A-Z(])/);
function orientPhrases(notes){const out=[];const re=/\b(aligned|orientated|oriented|orientation|axis|faces|facing|opens?|opening|entrance)\b[^.]{0,28}?\b(N|NNE|NE|ENE|E|ESE|SE|SSE|S|SSW|SW|WSW|W|WNW|NW|NNW)\b(?:\s*[-–]\s*(N|NNE|NE|ENE|E|ESE|SE|SSE|S|SSW|SW|WSW|W|WNW|NW|NNW)\b)?/;
  for(const s of sentences(notes)){if(/\b(field|wall|road|boundary|slope|stream|river|fence|hedge|ditch|lane|track|bank|ridge|valley|house|farm)\b/i.test(s))continue;const m=re.exec(s);if(m){out.push({text:s.trim(),a:m[2],b:m[3]||null,facing:/faces|facing|opens?|opening|entrance/.test(m[1])});if(out.length>=2)break;}}return out;}
function datePhrases(notes){return sentences(notes).filter(s=>/radiocarbon|\bdated\b|\bdate range\b|\b\d{3,4}\s?(?:-|–)\s?\d{3,4}\s?BC\b|cal\.? BC|excavat/i.test(s)).slice(0,3);}
function eventDecs(year){const e=A.obliquity(year),i=A.I_MOON;return [['midwinter Sun',-e],['midsummer Sun',e],['equinox Sun',0],['Moon, major standstill (north)',e+i],['Moon, major standstill (south)',-(e+i)],['Moon, minor standstill (north)',e-i],['Moon, minor standstill (south)',-(e-i)]];}
function matchAxis(az,lat,year,prof){const ds=[-11.25,0,11.25].map(d=>decOf(az+d,lat,prof));const lo=Math.min(...ds),hi=Math.max(...ds);return {dec:decOf(az,lat,prof),lo,hi,hits:eventDecs(year).filter(([,d])=>d>=lo-0.5&&d<=hi+0.5).map(x=>x[0])};}
const fmt=d=>(d>=0?'+':'−')+Math.abs(d).toFixed(1)+'°';

/* ---------- generic (all ~6,900 monuments) ---------- */
async function generic(q,s,ctx){
  const g=s[1],G=ctx.META.groups[g],K=(await kb()).scope[g]||null,ni=s[0].startsWith('NI:'),nt=await notesFor(s);const notes=nt?nt[0]:'',care=nt?nt[1]:null;
  const cls=G.en.replace(/s$/,'').replace(/tombs \(/,'tomb (').toLowerCase();
  if(q==='face'){
    const [yr,lab]=ERA[g]||[-1999,'c. 2000 BC'];const hz=s._hz||null,pr=hz?hz.alt:null;const ev=A.events(s[2],pr,yr).filter(e=>e.az!=null);
    const pick=['WS rise','WS set','SS rise','SS set','EQ rise','MjS rise','MjS set'];
    let h=`<p>No one has measured this monument’s orientation in our sources, so it is <b>not known</b> whether it faces a sunrise or moonrise. Here is where the key events happen from this spot ${hz?`on its <b>real horizon</b> (Copernicus 30 m surface model, which includes trees and buildings)`:'on a <b>flat horizon</b>'}, using Earth’s tilt for ${esc(lab)}:</p><ul class="ask-ev">${ev.filter(e=>pick.includes(e.k)).map(e=>`<li><span>${esc(e.en.replace(' (δ = 0°)',''))}</span><b>${e.az.toFixed(0)}° ${pt16(e.az)}</b></li>`).join('')}</ul>`;
    const op=orientPhrases(notes);const keys=['smr'];
    if(op.length){h+=`<p>The SMR description records:</p>`+op.map(o=>{const a=PT16[o.a];const m1=matchAxis(a,s[2],yr,pr);let t=`<blockquote>“${esc(o.text)}”</blockquote><p class="ask-calc">${o.b?`Axis ${o.a}–${o.b}`:`${o.facing?'Facing':'Towards'} ${o.a}`}: a ${o.a} bearing (${a}° ± 11°, since compass points are 22.5° apart) gives a declination of ${fmt(m1.lo)} to ${fmt(m1.hi)}`;
      if(o.b){const m2=matchAxis(PT16[o.b],s[2],yr,pr);t+=`; ${o.b} gives ${fmt(m2.lo)} to ${fmt(m2.hi)}`;const hits=[...new Set(m1.hits.concat(m2.hits))];t+=`. That range includes: ${hits.length?esc(hits.join(', ')):'none of the solar or lunar targets'}.`;}
      else t+=`. That range includes: ${m1.hits.length?esc(m1.hits.join(', ')):'none of the solar or lunar targets'}.`;
      return t+` <span class="muted">A compass phrase is far too coarse to prove intent.</span></p>`;}).join('');}
    else if(!ni)h+=`<p class="muted">The SMR description gives no compass orientation for this monument.</p>`;
    const to=TYPE_ORIENT[g];if(to){h+=`<p><b>For ${esc(G.en.toLowerCase())} in general:</b> ${esc(to[0])}</p>`;keys.push(...to[1]);}
    return {h,keys:ni?['nismr',...keys.filter(k=>k!=='smr')]:keys};}
  if(q==='when'){
    let h=K?`<p><b>The class.</b> In the NMS definition of a ${esc(cls)}: “${esc(K.en.replace(/ See also.*$/,''))}”</p>`:'<p>Our sources give no class date.</p>';
    const dp=datePhrases(notes);
    h+=dp.length?`<p><b>This monument.</b> Its SMR description mentions excavation or dating:</p>${dp.map(x=>`<blockquote>“${esc(x)}”</blockquote>`).join('')}`:`<p><b>This monument.</b> ${ni?'The NI record we hold has no description.':'The SMR description we hold mentions no excavation or date.'} Its own date is therefore <b>not known</b>, so the class range is the best guide.</p>`;
    h+=`<p><b>Who.</b> The builders’ names, language and identity are <b>not known</b>. The people who built them left no writing, only the monuments and what excavation finds.</p>`;
    return {h,keys:ni?['scope','nismr']:['scope','smr']};}
  if(q==='real'){
    const to=TYPE_ORIENT[g],t=TEST[g];
    let h=`<p>For a single monument, an alignment cannot be proved or disproved: with 12 solar and lunar targets on the horizon, almost any direction lands near one of them. The honest answer comes from <b>groups</b> of monuments, compared against random orientations.</p>`;
    if(to)h+=`<p><b>What is known for ${esc(G.en.toLowerCase())}:</b> ${esc(to[0])}</p>`;
    if(t){const R=await tres(),ids=(t.match(/T\d/g)||[]);const vs=R?ids.map(k=>{const v=R.tests[k];return v?`${k}: <b>${v.supported?'supported':'not supported'}</b> (Holm-adjusted p = ${v.p_holm<0.001?v.p_holm.toFixed(4):v.p_holm.toFixed(3)})`:'';}).filter(Boolean).join('; '):'';
      h+=`<p><b>Our test:</b> ${esc(t)} was written down in advance (pre-registered) with its pass rule, and scored on 9 Oct 2026. ${vs?`Result: ${vs}. `:''}<a href="results.html">See the full results</a>.</p>`;}
    h+=`<p>This monument has not been surveyed individually in our sources, so for it the answer is <b>not known</b>.</p>`;
    return {h,keys:[...(to?to[1]:[]),'research']};}
  if(q==='name'){
    const tl=String(s[4]||'').replace(/\b\w+/g,w=>w[0]+w.slice(1).toLowerCase());let h='';
    h+=s[5]?`<p>The townland is <b lang="ga">${esc(s[5])}</b> in Irish and <b>${esc(tl)}</b> in English. These are the statutory forms from Tailte Éireann.</p>`:`<p>The townland is <b>${esc(tl)}</b>. ${ni?'Our Northern Ireland data has no Irish townland names':'We could not match an Irish form for this townland'}, so it is <b>not known</b> here.</p>`;
    h+=`<p><b>What it means.</b> Our data does not explain townland names, so the meaning is <b>not known</b> here. Logainm.ie, the official placenames database, often gives the historical forms and an explanation: <a href="https://www.logainm.ie/en/s?txt=${encodeURIComponent(s[5]||tl)}" target="_blank" rel="noopener">look up ${esc(s[5]||tl)} ↗</a>.</p>`;
    if(K&&K.ga_name)h+=`<p><b>The monument type in Irish:</b> <i lang="ga">${esc(K.ga_name)}</i> (NMS official term).</p>`;
    const cg=ctx.META.counties_ga[s[6]];if(cg)h+=`<p><b>County:</b> <i lang="ga">${esc(cg)}</i>.</p>`;
    return {h,keys:['tailte','logainm','scope']};}
  if(q==='visit'){
    let h='';
    if(care)h+=`<p><b>This monument is in State care</b> (${esc(care||'listed')}), according to the NMS list of National Monuments in State Care. Note that this list dates from 2009, and not every monument in State care has public access. Check heritageireland.ie before you go.</p>`;
    else h+=`<p>This monument is <b>not</b> in the 2009 NMS list of monuments in State care. Most monuments are on <b>private land</b>: ask the landowner’s permission, close gates, and don’t climb on the stones. Access details are <b>not known</b> from our data.</p>`;
    if(notes){const n=notes.replace(/\n*(Compiled by|Date of upload|The above description is derived)[\s\S]*$/,'').trim();h+=`<p><b>What the surveyors recorded</b> (SMR description):</p><blockquote class="ask-notes">${esc(n.length>1400?n.slice(0,n.lastIndexOf('. ',1400)+1)+' …':n)}</blockquote>${s[0].startsWith('NI:')?'':`<p class="muted"><a href="${ctx.META.hev_link_prefix+encodeURIComponent(s[0])}" target="_blank" rel="noopener">Full record and photos in the Historic Environment Viewer ↗</a></p>`}`;}
    else h+=`<p>${ni?'The NI record we hold has no description; see the NI SMR for details.':'The SMR holds no description for this monument.'}</p>`;
    return {h,keys:care?['care','smr']:['smr',...(ni?['nismr']:[])]};}
}

/* ---------- featured sites: hand-written, every statement from the cited sources ---------- */
const F={
 newgrange:{
  face:['<p><b>Yes: the midwinter sunrise.</b> The roof-box above the entrance lets the rising Sun shine down the 19 m passage onto the chamber floor around the winter solstice.</p><p>On the real horizon (Copernicus 30 m surface model), first gleam is at about <b>134.3°</b> (SE) in 3200 BC and 133.1° today. NMS photography in 2020–21 found direct light in the chamber from 12 Dec to 8 Jan, for under 20 minutes each morning. The light enters for Sun azimuths of about 133.7°–138.4°, which is a declination of −23.8° to −25.9°.</p><p>The Moon is not part of the documented phenomenon.</p>',['ng2024','patrick','ray']],
  when:['<p>The NMS (2024) says Newgrange was <b>constructed around 3200 BC</b>. That fits the class range for passage tombs (3300–2900 BC). The builders’ names and language are <b>not known</b>.</p>',['ng2024','scope']],
  real:['<p><b>Strong evidence that it is real.</b> Tom Ray (1989) concluded the roof-box effect was “very probably designed”. It has been measured repeatedly: O’Kelly in 1969, Patrick in 1974, and the NMS in 2020–21.</p><p><b>Caveats.</b> The precision is modest, a window a few degrees wide, and Heggie doubted the early precision. Across Ireland, only 4 of 136 measured passage tombs face the midwinter sunrise, so Newgrange is an exception, not the rule.</p>',['ray','okelly','ng2024']],
  name:['<p>The monument stands in the townland of <b lang="ga">An Ghráinseach Nua</b> (Tailte Éireann). Word by word, this is <i>gráinseach</i>, “grange”, a farm house or monastic farm (focloir.ie), and <i>nua</i>, “new”: “the new grange”. The wider complex is <b lang="ga">Brú na Bóinne</b>.</p><p>The history of each name is on <a href="https://www.logainm.ie/en/s?txt=An%20Ghr%C3%A1inseach%20Nua" target="_blank" rel="noopener">logainm.ie ↗</a>.</p>',['tailte','focloir','logainm']],
  visit:['<p>Access is <b>only by guided tour from the Brú na Bóinne Visitor Centre</b>, with a shuttle bus to the monument, and <b>pre-booking is essential</b>. Do not drive to the monument itself. The tour includes the chamber.</p>',['hiBnB','ng2024']]},
 knowth:{
  face:['<p>The two passages of Knowth 1 open roughly <b>east and west</b>. Brennan (1983) proposed equinox alignments.</p><p>Prendergast and Ray (2015) surveyed them. The western passage is lit about 17 days after the autumn equinox, and its inner part points 8° north of the equinox sunset. The eastern passage is about 6 days off.</p>',['brennan','knowthPR']],
  when:['<p>Knowth is a passage tomb, a class dated mainly <b>3300–2900 BC</b> (NMS scope note). Our sources give no more exact construction date. The builders are <b>not known</b>.</p>',['scope']],
  real:['<p><b>Not supported as an equinox design.</b> The surveyed passages miss the equinox by days to weeks (Prendergast & Ray 2015). They face broadly east and west, but that is not evidence of a precise equinox target.</p>',['knowthPR','knowthLS']],
  name:['<p>The townland is <b lang="ga">Cnóbha</b> in Irish and Knowth in English (Tailte Éireann). Its meaning is <b>not known</b> from our sources; logainm.ie gives the historical forms: <a href="https://www.logainm.ie/en/s?txt=Cn%C3%B3bha" target="_blank" rel="noopener">Cnóbha ↗</a>.</p>',['tailte','logainm']],
  visit:['<p>Access is <b>only by guided tour from the Brú na Bóinne Visitor Centre</b>, and pre-booking is essential. Knowth is included in the main-season tour and closed from early November to the end of February. You can see the great mound, its kerb of decorated stones, and the smaller satellite tombs around it.</p>',['hiBnB']]},
 dowth:{
  face:['<p><b>The low winter sunset.</b> Anne-Marie Moroney (1999) photographed the setting Sun entering the southern chamber from October to February.</p>',['moroney']],
  when:['<p>Dowth is a passage tomb (class date 3300–2900 BC). Our sources give no more exact date, and the builders are <b>not known</b>.</p>',['scope']],
  real:['<p>The light entering the chamber is <b>observed</b> and photographed. Whether it was intended has not been tested, so that part is <b>not known</b>.</p>',['moroney']],
  name:['<p>The townland is <b lang="ga">Dubhadh</b> in Irish and Dowth in English (Tailte Éireann). Its meaning is <b>not known</b> from our sources: <a href="https://www.logainm.ie/en/s?txt=Dubhadh" target="_blank" rel="noopener">see logainm.ie ↗</a>.</p>',['tailte','logainm']],
  visit:['<p>Dowth is part of Brú na Bóinne. We do not hold verified, current access details for Dowth, so check with Heritage Ireland before you go.</p>',['hiBnB']]},
 cairnT:{
  face:['<p>Cairn T is famous for the <b>equinox sunrise</b> lighting its decorated backstone. Prendergast gives the passage a declination of about −1°, close to the equinox Sun (0°).</p>',['loughcrewFP','hiLC']],
  when:['<p>Heritage Ireland dates the Loughcrew tombs to about <b>3000 BC</b>. That is within the passage-tomb range of 3300–2900 BC given by the NMS. The builders are <b>not known</b>.</p>',['hiLC','scope']],
  real:['<p><b>Debated.</b> The light show is real, but the entrance and roof were altered in OPW restoration, which may have changed how the light enters (Cochrane, citing McMann 1994).</p>',['cochrane','loughcrewFP']],
  name:['<p>Cairn T stands in the townland of <b lang="ga">Baile an Chorraigh</b> (Corstown) (Tailte Éireann). Its meaning is <b>not known</b> from our sources: <a href="https://www.logainm.ie/en/s?txt=Baile%20an%20Chorraigh" target="_blank" rel="noopener">see logainm.ie ↗</a>.</p>',['tailte','logainm']],
  visit:['<p>The hill is <b>open all year</b>, but <b>the interior of Cairn T has been closed since October 2018</b> for conservation and safety work, and it stays closed for the 2026 season.</p><p>The climb is very steep, so wear sturdy footwear. There is no wheelchair access. Please don’t climb on the cairn.</p>',['hiLC','oirLC']]},
 carrowmore:{
  face:['<p>Listoghil (Carrowmore 51) has been linked to sunrise around <b>Samhain and Imbolc</b> (about 31 Oct and 10 Feb). This comes from observation (Meehan 2012), not from a statistical test.</p>',['meehan']],
  when:['<p>The NMS scope note says some simpler tombs at Carrowmore have radiocarbon dates suggesting use as early as <b>c. 4000 BC</b>, earlier than the main passage-tomb period of 3300–2900 BC. Those early dates are disputed. The builders are <b>not known</b>.</p>',['scope']],
  real:['<p><b>Proposed only.</b> The alignment has been observed but not tested against chance.</p>',['meehan']],
  name:['<p>The townland is <b lang="ga">An Cheathrú Mhór</b> in Irish and Carrowmore in English (Tailte Éireann). Word by word: <i>ceathrú</i>, “quarter”, and <i>mór</i>, “big” (focloir.ie). For the history of the name, see <a href="https://www.logainm.ie/en/s?txt=An%20Cheathr%C3%BA%20Mh%C3%B3r" target="_blank" rel="noopener">logainm.ie ↗</a>.</p>',['tailte','focloir','logainm']],
  visit:['<p>The OPW <b>visitor centre</b> was upgraded and reopened on 1 April 2026. In 2026 it is open 12 March to 2 December, 10:00–18:00 (last admission 17:00), with guided tours. Admission is €5 for adults. More than 30 tombs survive across the fields.</p>',['hiCM']]},
 carrowkeelG:{
  face:['<p>Martin Byrne observed and photographed the <b>midsummer sunset</b> shining through Cairn G’s roof-box, and reported the Moon too (BBC 1999).</p>',['carrowkeel','bbc1999']],
  when:['<p>Cairn G is a passage tomb (class date 3300–2900 BC, NMS). Our sources give no more exact date, and the builders are <b>not known</b>.</p>',['scope']],
  real:['<p>The light effect is <b>observed</b>. Whether it was intended has not been tested.</p>',['carrowkeel']],
  name:['<p>The townland is <b lang="ga">An Cheathrú Chaol</b> in Irish and Carrowkeel in English (Tailte Éireann). Word by word: <i>ceathrú</i>, “quarter”, and <i>caol</i>, “narrow” (focloir.ie). For the history of the name, see <a href="https://www.logainm.ie/en/s?txt=An%20Cheathr%C3%BA%20Chaol" target="_blank" rel="noopener">logainm.ie ↗</a>.</p>',['tailte','focloir','logainm']],
  visit:['<p>Access details are <b>not known</b> from our sources. The tombs are on exposed hilltops: check current local guidance and respect the monuments.</p>',[]]},
 drombeg:{
  face:['<p>The circle’s axis runs <b>NE–SW</b> (SMR). The axial stone lies towards the south-west, which has been linked to the <b>midwinter sunset</b>.</p><p>When Fahy watched it in 1957 and 1958, the Sun set slightly south of the axis.</p>',['fahy','smr','hiDB']],
  when:['<p>Charcoal from the burial pit inside the circle has been dated to <b>1124–794 BC</b> (Waddell 1998, cited in the SMR). Earlier radiocarbon results were judged anomalous. That fits the Bronze Age class date of 2400–500 BC. The builders are <b>not known</b>.</p>',['smr','scope']],
  real:['<p><b>Debated.</b> Ruggles (1994) tested 31 axial-stone circles and found no solar pattern, so Drombeg’s alignment could be chance.</p>',['ruggles94','fahy']],
  name:['<p>The townland is <b lang="ga">An Drom Beag</b> in Irish and Drombeg in English (Tailte Éireann). <i>Beag</i> means “small”, and <i>drom</i> looks like <i>droim</i>, “ridge” (focloir.ie). Logainm.ie has the authoritative explanation: <a href="https://www.logainm.ie/en/s?txt=An%20Drom%20Beag" target="_blank" rel="noopener">see logainm.ie ↗</a>.</p>',['tailte','focloir','logainm']],
  visit:['<p>Drombeg is a <b>National Monument in State guardianship</b> and an unguided site, less than 3 km east of Glandore.</p><p>You can see 15 of the original 17 stones still standing or fallen, the axial stone with two cup-marks, and the nearby hut site and <i>fulacht fia</i> (cooking place).</p>',['hiDB','smr']]},
 beltany:{
  face:['<p>Ken Williams photographed the <b>Bealtaine (early May) sunrise</b> over Tullyrap from the circle. There is no statistical study.</p>',['beltanyW']],
  when:['<p>Beltany is a stone circle, a class the NMS dates mainly to the Bronze Age (c. 2400–500 BC), with possible Neolithic origins. Its own date is <b>not known</b> from our sources.</p>',['scope']],
  real:['<p><b>Proposed only.</b> The alignment has been photographed but not tested against chance.</p>',['beltanyW']],
  name:['<p>The townland is <b>Tops</b>. Tailte Éireann gives no Irish form for it, so the Irish name is <b>not known</b> here. The name “Beltany” is often linked with Bealtaine, but our sources do not confirm this.</p>',['tailte']],
  visit:['<p>Access details are <b>not known</b> from our sources. Check locally and respect the stones.</p>',[]]}
};

function panel(s,f){
  return `<section class="ask" aria-label="Ask PA Réalt"><h3 class="ask-h"><span class="ga" lang="ga">Fiafraigh</span> Ask PA Réalt</h3>
  <div class="ask-qs" role="group">${QS.map(([k,en,ga])=>`<button type="button" class="ask-q" data-q="${k}" aria-expanded="false"><span>${esc(en)}</span><i lang="ga">${esc(ga)}</i></button>`).join('')}</div>
  <div class="ask-a" aria-live="polite"></div>
  <div class="ask-deep"><button type="button" class="deep-btn" disabled aria-disabled="true"><span class="ga" lang="ga">Freagra domhain</span> Deep answer <span class="soon">Coming soon</span></button>
  <p class="muted">A planned paid option: an AI analysis of this monument, grounded in this site’s data and with every claim cited, for about €0.50–€1. It is not live, and no payment is taken.</p></div></section>`;}
function bind(root,s,f,ctx){
  const box=root.querySelector('.ask');if(!box)return;const out=box.querySelector('.ask-a');
  box.addEventListener('click',async e=>{const b=e.target.closest('.ask-q');if(!b)return;const q=b.dataset.q;
    const was=b.getAttribute('aria-expanded')==='true';box.querySelectorAll('.ask-q').forEach(x=>x.setAttribute('aria-expanded','false'));
    if(was){out.innerHTML='';return;}b.setAttribute('aria-expanded','true');out.innerHTML='<p class="muted">…</p>';
    let r;const fx=f&&F[f.key]&&F[f.key][q];
    try{r=fx?{h:fx[0],keys:fx[1]}:await generic(q,s,ctx);}catch(err){r={h:'<p>Sorry, this answer could not be loaded.</p>',keys:[]};}
    out.innerHTML=`<div class="ask-ans">${r.h}${r.keys.length?`<p class="ask-src">Sources: ${src([...new Set(r.keys)])}</p>`:''}<p class="ask-foot">${fx?'Hand-written for this featured site.':'Built from this site’s data. No AI.'}</p></div>`;
    if(innerWidth<900)out.scrollIntoView({behavior:'smooth',block:'nearest'});});
}
window.PAAsk={panel,bind,F,src};
})();
